spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
  error:
    include-stacktrace: never